<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XEjFHUzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xEjFHUz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xEjFHUz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'detalleCompra' => ['privates', '.errored..service_locator.xEjFHUz.App\\Entity\\DetalleCompra', NULL, 'Cannot autowire service ".service_locator.xEjFHUz": it needs an instance of "App\\Entity\\DetalleCompra" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'detalleCompra' => 'App\\Entity\\DetalleCompra',
            'entityManager' => '?',
        ]);
    }
}
