<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarritoControllermostrarCarritoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BfJpID0.App\Controller\CarritoController::mostrarCarrito()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BfJpID0.App\\Controller\\CarritoController::mostrarCarrito()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['services', 'request_stack', 'getRequestStackService', false],
        ], [
            'request' => '?',
        ]))->withContext('App\\Controller\\CarritoController::mostrarCarrito()', $container);
    }
}
