<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComprasManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ComprasManager' shared autowired service.
     *
     * @return \App\Service\ComprasManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ComprasManager.php';

        return $container->privates['App\\Service\\ComprasManager'] = new \App\Service\ComprasManager(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\DetalleCompraRepository'] ?? $container->load('getDetalleCompraRepositoryService')), ($container->privates['App\\Repository\\PedidosRepository'] ?? $container->load('getPedidosRepositoryService')), ($container->privates['App\\Repository\\GafasRepository'] ?? $container->load('getGafasRepositoryService')), ($container->privates['App\\Repository\\LentillasRepository'] ?? $container->load('getLentillasRepositoryService')), ($container->privates['App\\Repository\\DetallePedidoRepository'] ?? $container->load('getDetallePedidoRepositoryService')));
    }
}
