<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarritoControllereliminarProductoActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HPrje7G.App\Controller\CarritoController::eliminarProductoAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HPrje7G.App\\Controller\\CarritoController::eliminarProductoAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carritoManager' => ['privates', 'App\\Service\\CarritoManager', 'getCarritoManagerService', true],
        ], [
            'carritoManager' => 'App\\Service\\CarritoManager',
        ]))->withContext('App\\Controller\\CarritoController::eliminarProductoAction()', $container);
    }
}
