<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetalleCompraControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xEjFHUz.App\Controller\DetalleCompraController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xEjFHUz.App\\Controller\\DetalleCompraController::delete()'] = ($container->privates['.service_locator.xEjFHUz'] ?? $container->load('get_ServiceLocator_XEjFHUzService'))->withContext('App\\Controller\\DetalleCompraController::delete()', $container);
    }
}
