<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGafasCrudControllerconfigureAssetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.49XXFvZ.App\Controller\Admin\GafasCrudController::configureAssets()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.49XXFvZ.App\\Controller\\Admin\\GafasCrudController::configureAssets()'] = ($container->privates['.service_locator.49XXFvZ'] ?? $container->load('get_ServiceLocator_49XXFvZService'))->withContext('App\\Controller\\Admin\\GafasCrudController::configureAssets()', $container);
    }
}
