<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGafasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SvCRvdx.App\Entity\Gafas' shared service.
     *
     * @return \App\Entity\Gafas
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SvCRvdx": it needs an instance of "App\\Entity\\Gafas" but this type has been excluded in "config/services.yaml".');
    }
}
