<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedidosControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5qTdY6j.App\Controller\PedidosController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5qTdY6j.App\\Controller\\PedidosController::delete()'] = ($container->privates['.service_locator.5qTdY6j'] ?? $container->load('get_ServiceLocator_5qTdY6jService'))->withContext('App\\Controller\\PedidosController::delete()', $container);
    }
}
