<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedidosControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5qTdY6j.App\Controller\PedidosController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.5qTdY6j'] ?? $container->load('get_ServiceLocator_5qTdY6jService'));

        if (isset($container->privates['.service_locator.5qTdY6j.App\\Controller\\PedidosController::edit()'])) {
            return $container->privates['.service_locator.5qTdY6j.App\\Controller\\PedidosController::edit()'];
        }

        return $container->privates['.service_locator.5qTdY6j.App\\Controller\\PedidosController::edit()'] = $a->withContext('App\\Controller\\PedidosController::edit()', $container);
    }
}
