<?php

namespace ContainerUQw9p22;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedidosControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eAGcXCP.App\Controller\PedidosController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eAGcXCP.App\\Controller\\PedidosController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pedidosRepository' => ['privates', 'App\\Repository\\PedidosRepository', 'getPedidosRepositoryService', true],
        ], [
            'pedidosRepository' => 'App\\Repository\\PedidosRepository',
        ]))->withContext('App\\Controller\\PedidosController::index()', $container);
    }
}
