<?php

namespace ContainerRb2rJFP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SD_NhdnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SD.nhdn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SD.nhdn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'detallePedido' => ['privates', '.errored..service_locator.SD.nhdn.App\\Entity\\DetallePedido', NULL, 'Cannot autowire service ".service_locator.SD.nhdn": it needs an instance of "App\\Entity\\DetallePedido" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'detallePedido' => 'App\\Entity\\DetallePedido',
            'entityManager' => '?',
        ]);
    }
}
