<?php

namespace ContainerRb2rJFP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetallePedidoControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SD.nhdn.App\Controller\DetallePedidoController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.SD.nhdn'] ?? $container->load('get_ServiceLocator_SD_NhdnService'));

        if (isset($container->privates['.service_locator.SD.nhdn.App\\Controller\\DetallePedidoController::edit()'])) {
            return $container->privates['.service_locator.SD.nhdn.App\\Controller\\DetallePedidoController::edit()'];
        }

        return $container->privates['.service_locator.SD.nhdn.App\\Controller\\DetallePedidoController::edit()'] = $a->withContext('App\\Controller\\DetallePedidoController::edit()', $container);
    }
}
