vich_uploader:
    db_driver: orm

    mappings:
        user:
            uri_prefix: /documentos/usuarios
            upload_destination: '%kernel.project_dir%/public/documentos/usuarios'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
