vich_uploader:
    db_driver: orm

    mappings:
        user:
            uri_prefix: /documentos/usuarios
            upload_destination: '%kernel.project_dir%/public/documentos/usuarios'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


        gafas:
            uri_prefix: /images/gafas
            upload_destination: '%kernel.project_dir%/public/images/gafas'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


        campania:
            uri_prefix: /campania
            upload_destination: '%kernel.project_dir%/public/campania'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


        lentillas:
            uri_prefix: /images/lentillas
            upload_destination: '%kernel.project_dir%/public/images/lentillas'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
