<?php

namespace ContainerP5AZiK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ma8QXqCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ma8QXqC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ma8QXqC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lentilla' => ['privates', '.errored..service_locator.ma8QXqC.App\\Entity\\Lentillas', NULL, 'Cannot autowire service ".service_locator.ma8QXqC": it needs an instance of "App\\Entity\\Lentillas" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'lentilla' => 'App\\Entity\\Lentillas',
            'entityManager' => '?',
        ]);
    }
}
