<?php

namespace ContainerP5AZiK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BBYunBrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bBYunBr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bBYunBr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gafa' => ['privates', '.errored..service_locator.bBYunBr.App\\Entity\\Gafas', NULL, 'Cannot autowire service ".service_locator.bBYunBr": it needs an instance of "App\\Entity\\Gafas" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'gafa' => 'App\\Entity\\Gafas',
            'entityManager' => '?',
        ]);
    }
}
