<?php

namespace ContainerP5AZiK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaniasControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EL2nvVV.App\Controller\CampaniasController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EL2nvVV.App\\Controller\\CampaniasController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'campania' => ['privates', '.errored..service_locator.EL2nvVV.App\\Entity\\Campanias', NULL, 'Cannot autowire service ".service_locator.EL2nvVV": it needs an instance of "App\\Entity\\Campanias" but this type has been excluded in "config/services.yaml".'],
        ], [
            'campania' => 'App\\Entity\\Campanias',
        ]))->withContext('App\\Controller\\CampaniasController::show()', $container);
    }
}
