<?php

namespace ContainerP5AZiK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaniasControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uKWj9N6.App\Controller\CampaniasController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uKWj9N6.App\\Controller\\CampaniasController::delete()'] = ($container->privates['.service_locator.uKWj9N6'] ?? $container->load('get_ServiceLocator_UKWj9N6Service'))->withContext('App\\Controller\\CampaniasController::delete()', $container);
    }
}
