<?php

namespace ContainerP5AZiK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaniasControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DVPulIL.App\Controller\CampaniasController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DVPulIL.App\\Controller\\CampaniasController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'campaniasRepository' => ['privates', 'App\\Repository\\CampaniasRepository', 'getCampaniasRepositoryService', true],
        ], [
            'campaniasRepository' => 'App\\Repository\\CampaniasRepository',
        ]))->withContext('App\\Controller\\CampaniasController::index()', $container);
    }
}
