<?php

namespace ContainerP5AZiK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGafasControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mTa2BeV.App\Controller\GafasController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mTa2BeV.App\\Controller\\GafasController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gafasRepository' => ['privates', 'App\\Repository\\GafasRepository', 'getGafasRepositoryService', true],
        ], [
            'gafasRepository' => 'App\\Repository\\GafasRepository',
        ]))->withContext('App\\Controller\\GafasController::index()', $container);
    }
}
