<?php

namespace ContainerP5AZiK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLentillasControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dTZ_OXT.App\Controller\LentillasController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dTZ_OXT.App\\Controller\\LentillasController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lentilla' => ['privates', '.errored..service_locator.dTZ_OXT.App\\Entity\\Lentillas', NULL, 'Cannot autowire service ".service_locator.dTZ_OXT": it needs an instance of "App\\Entity\\Lentillas" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lentilla' => 'App\\Entity\\Lentillas',
        ]))->withContext('App\\Controller\\LentillasController::show()', $container);
    }
}
