<?php

namespace ContainerP5AZiK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLentillasControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Xd2oeS.App\Controller\LentillasController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Xd2oeS.App\\Controller\\LentillasController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lentillasRepository' => ['privates', 'App\\Repository\\LentillasRepository', 'getLentillasRepositoryService', true],
        ], [
            'lentillasRepository' => 'App\\Repository\\LentillasRepository',
        ]))->withContext('App\\Controller\\LentillasController::index()', $container);
    }
}
