<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'apellido1' => [parent::class, 'apellido1', null],
        "\0".parent::class."\0".'apellido2' => [parent::class, 'apellido2', null],
        "\0".parent::class."\0".'ciudad' => [parent::class, 'ciudad', null],
        "\0".parent::class."\0".'cp' => [parent::class, 'cp', null],
        "\0".parent::class."\0".'detalleCompras' => [parent::class, 'detalleCompras', null],
        "\0".parent::class."\0".'direccion' => [parent::class, 'direccion', null],
        "\0".parent::class."\0".'documentFile' => [parent::class, 'documentFile', null],
        "\0".parent::class."\0".'documentName' => [parent::class, 'documentName', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'pedidos' => [parent::class, 'pedidos', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'apellido1' => [parent::class, 'apellido1', null],
        'apellido2' => [parent::class, 'apellido2', null],
        'ciudad' => [parent::class, 'ciudad', null],
        'cp' => [parent::class, 'cp', null],
        'detalleCompras' => [parent::class, 'detalleCompras', null],
        'direccion' => [parent::class, 'direccion', null],
        'documentFile' => [parent::class, 'documentFile', null],
        'documentName' => [parent::class, 'documentName', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'isVerified' => [parent::class, 'isVerified', null],
        'nombre' => [parent::class, 'nombre', null],
        'password' => [parent::class, 'password', null],
        'pedidos' => [parent::class, 'pedidos', null],
        'roles' => [parent::class, 'roles', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
