<?php

namespace ContainerSzs3fc0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UKWj9N6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uKWj9N6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uKWj9N6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'campania' => ['privates', '.errored..service_locator.uKWj9N6.App\\Entity\\Campanias', NULL, 'Cannot autowire service ".service_locator.uKWj9N6": it needs an instance of "App\\Entity\\Campanias" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'campania' => 'App\\Entity\\Campanias',
            'entityManager' => '?',
        ]);
    }
}
