<?php

namespace ContainerSzs3fc0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaniasControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uKWj9N6.App\Controller\CampaniasController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.uKWj9N6'] ?? $container->load('get_ServiceLocator_UKWj9N6Service'));

        if (isset($container->privates['.service_locator.uKWj9N6.App\\Controller\\CampaniasController::edit()'])) {
            return $container->privates['.service_locator.uKWj9N6.App\\Controller\\CampaniasController::edit()'];
        }

        return $container->privates['.service_locator.uKWj9N6.App\\Controller\\CampaniasController::edit()'] = $a->withContext('App\\Controller\\CampaniasController::edit()', $container);
    }
}
