<?php

namespace ContainerSzs3fc0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGafasControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bBYunBr.App\Controller\GafasController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bBYunBr.App\\Controller\\GafasController::delete()'] = ($container->privates['.service_locator.bBYunBr'] ?? $container->load('get_ServiceLocator_BBYunBrService'))->withContext('App\\Controller\\GafasController::delete()', $container);
    }
}
