<?php

namespace ContainerSzs3fc0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGafasControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bBYunBr.App\Controller\GafasController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.bBYunBr'] ?? $container->load('get_ServiceLocator_BBYunBrService'));

        if (isset($container->privates['.service_locator.bBYunBr.App\\Controller\\GafasController::edit()'])) {
            return $container->privates['.service_locator.bBYunBr.App\\Controller\\GafasController::edit()'];
        }

        return $container->privates['.service_locator.bBYunBr.App\\Controller\\GafasController::edit()'] = $a->withContext('App\\Controller\\GafasController::edit()', $container);
    }
}
