<?php

namespace ContainerSzs3fc0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLentillas2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ma8QXqC.App\Entity\Lentillas' shared service.
     *
     * @return \App\Entity\Lentillas
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ma8QXqC": it needs an instance of "App\\Entity\\Lentillas" but this type has been excluded in "config/services.yaml".');
    }
}
