<?php

namespace ContainerLiznIm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetallePedidoControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qIb5NHd.App\Controller\DetallePedidoController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qIb5NHd.App\\Controller\\DetallePedidoController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'detallePedido' => ['privates', '.errored..service_locator.qIb5NHd.App\\Entity\\DetallePedido', NULL, 'Cannot autowire service ".service_locator.qIb5NHd": it needs an instance of "App\\Entity\\DetallePedido" but this type has been excluded in "config/services.yaml".'],
        ], [
            'detallePedido' => 'App\\Entity\\DetallePedido',
        ]))->withContext('App\\Controller\\DetallePedidoController::show()', $container);
    }
}
