<?php

namespace ContainerLiznIm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetallePedidoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SD.nhdn.App\Entity\DetallePedido' shared service.
     *
     * @return \App\Entity\DetallePedido
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SD.nhdn": it needs an instance of "App\\Entity\\DetallePedido" but this type has been excluded in "config/services.yaml".');
    }
}
