<?php

namespace ContainerLiznIm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetallePedidoControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._VwCqBO.App\Controller\DetallePedidoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._VwCqBO.App\\Controller\\DetallePedidoController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'detallePedidoRepository' => ['privates', 'App\\Repository\\DetallePedidoRepository', 'getDetallePedidoRepositoryService', true],
        ], [
            'detallePedidoRepository' => 'App\\Repository\\DetallePedidoRepository',
        ]))->withContext('App\\Controller\\DetallePedidoController::index()', $container);
    }
}
