<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQGNccDU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQGNccDU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQGNccDU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQGNccDU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQGNccDU\App_KernelDevDebugContainer([
    'container.build_hash' => 'QGNccDU',
    'container.build_id' => 'f7aea537',
    'container.build_time' => 1729890494,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQGNccDU');
