<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSzs3fc0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSzs3fc0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSzs3fc0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSzs3fc0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSzs3fc0\App_KernelDevDebugContainer([
    'container.build_hash' => 'Szs3fc0',
    'container.build_id' => '85997406',
    'container.build_time' => 1728120637,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSzs3fc0');
